# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "prevoty/fedora-23"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 6543, host: 6543
  config.vm.network "forwarded_port", guest: 5984, host: 5984

  config.vm.provision "shell", path: "https://raw.githubusercontent.com/gorserg/openprocurement.buildout/deploy_app/deploy_op.sh"
end
